### ISSUE TITLE
Title Screen To-Do's:

### ISSUE THREAD

**Issue by ShotgunJ0ker** [ShotgunJ0ker/ffna-haxe#1]
- [x] Add Logo, Buttons, Static, Freddy, and Credits.
- [x] Make Freddy twitch and add random effect flickers for certain objects.
- [ ] Add the strange, slow, scrolling bar from top to bottom, repeating.
- [ ] Make Buttons work and fully able to be selected. (Hovering over & Arrow Keys)

## **DEVELOPMENT PERIODS: _3/16/24 - ???_**

Code Programmed by VillianousJ0ker

**Comment by ShotgunJ0ker** [comment]
![Screenshot 2024-03-28 173616](https://github.com/ShotgunJ0ker/ffna-haxe/assets/153438815/555c85c8-5552-4e4e-abdb-f67e553faff5)

## Task 4 Finished.

Finished adding programmed buttons & are completely functional.
